import { Vector3 } from "three";
import type { Card, Player } from "@/types";
import { BOARD_SIZE, NORTH_BOARD_START, SOUTH_BOARD_START, EAST_BOARD_START, WEST_BOARD_START, PLAYER_BASE_Z } from "@/const";

export const cards: Card[] = [
  {
    id: 1,
    name: "Dark Magician",
    attack: 2500,
    defense: 2100,
    description: "The ultimate wizard in terms of attack and defense.",
    owner: "player",
    position: new Vector3(2, -5, 0.11),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 8,
    attribute: "Dark",
    attributeUrl: "/attributes/darkAttr.svg",
    textureUrl: "/cards/Dark_Magician.png",
    textureTemplateUrl: "/textures/normalTemplate.png",
    maskUrl: "/cards/Dark_Magician_Mask.png",
  },
  {
    id: 2,
    name: "Blue-Eyes White Dragon",
    attack: 3000,
    defense: 2500,
    description: "This legendary dragon is a powerful engine of destruction.",
    owner: "opponent",
    position: new Vector3(0, 4, 0.12),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 8,
    attribute: "Light",
    attributeUrl: "/attributes/lightAttr.svg",
    textureUrl: "/cards/Blue_Eyes_White_Dragon.png",
    textureTemplateUrl: "/textures/normalTemplate.png",
  },
  {
    id: 3,
    name: "Dark Magician Girl",
    attack: 2000,
    defense: 1600,
    description: "The Dark Magician's younger sister. She wields the power of the Dark Magician.",
    owner: "player",
    position: new Vector3(-2, -5, 0.13),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 6,
    attribute: "Dark",
    attributeUrl: "/attributes/darkAttr.svg",
    textureUrl: "/cards/Dark_Magician_Girl.png",
    textureTemplateUrl: "/textures/effectTemplate.png",
    maskUrl: "/cards/Dark_Magician_Girl_Mask.png",
  },
  {
    id: 4,
    name: "Red-Eyes Black Dragon",
    attack: 2400,
    defense: 2000,
    description: "A ferocious dragon with a deadly attack.",
    owner: "opponent",
    position: new Vector3(2, 5, 0.14),
    isFaceDown: false,
    isDefenseMode: false,
    rarity: "common",
    level: 7,
    attribute: "Dark",
    attributeUrl: "/attributes/darkAttr.svg",
    textureUrl: "/cards/Red_Eyes_Black_Dragon.png",
    textureTemplateUrl: "/textures/normalTemplate.png",
  },
  {
    id: 5,
    name: "Blue-Eyes White Dragon",
    attack: 3000,
    defense: 2500,
    description: "This legendary dragon is a powerful engine of destruction.",
    owner: "player",
    position: new Vector3(0, -2, 0.12),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 8,
    attribute: "Light",
    attributeUrl: "/attributes/lightAttr.svg",
    textureUrl: "/cards/Blue_Eyes_White_Dragon.png",
    textureTemplateUrl: "/textures/normalTemplate.png",
    maskUrl: "/cards/Blue_Eyes_White_Dragon_Mask.png",
  },
  {
    id: 6,
    name: "Blue-Eyes Ultimate Dragon",
    attack: 4500,
    defense: 3800,
    description: "This legendary dragon is a powerful engine of destruction.",
    owner: "player",
    position: new Vector3(1, -2, 0.12),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 12,
    attribute: "Light",
    attributeUrl: "/attributes/lightAttr.svg",
    textureUrl: "/cards/Blue_Eyes_Ultimate_Dragon.png",
    textureTemplateUrl: "/textures/fusionTemplate.png",
    maskUrl: "/cards/Blue_Eyes_Ultimate_Dragon_Mask.png",
  },
  {
    id: 7,
    name: "Black Luster Soldier",
    attack: 3000,
    defense: 2500,
    description: "This monster can only be Ritual Summoned with the Ritual Spell Card, Black Luster Ritual.",
    owner: "player",
    position: new Vector3(-1, -5, 0.13),
    isFaceDown: false,
    isDefenseMode: false,
    rarity: "common",
    level: 8,
    attribute: "Earth",
    attributeUrl: "/attributes/earthAttr.svg",
    textureUrl: "/cards/Black_Luster_Soldier.png",
    textureTemplateUrl: "/textures/ritualTemplate.png",
  },
  {
    id: 8,
    name: "Change of Heart",
    attack: -1,
    defense: -1,
    description: "Target 1 monster your opponent controls; change its ATK and DEF to 0.",
    owner: "player",
    position: new Vector3(0, -3, 0.11),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "common",
    level: 0,
    attribute: "Spell",
    attributeUrl: "/attributes/spellAttr.svg",
    textureUrl: "/cards/Change_of_Heart.png",
    textureTemplateUrl: "/textures/magicTemplate.png",
  },
  {
    id: 9,
    name: "Summoned Skull",
    attack: 2500,
    defense: 1200,
    description: "A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, the monster boasts considerable force.",
    owner: "player",
    position: new Vector3(0, -4, 0.11),
    isFaceDown: false,
    isDefenseMode: false,
    rarity: "ultra",
    level: 6,
    attribute: "Dark",
    attributeUrl: "/attributes/darkAttr.svg",
    textureUrl: "/cards/Summoned_Skull.png",
    textureTemplateUrl: "/textures/normalTemplate.png",
    maskUrl: "/cards/Summoned_Skull_Mask.png",
  }
];

export const players: Player[] = [
  {
    id: 100,
    name: "Player_1",
    clan: "Yorkists",
    textureUrl: "/textures/Red_rose_emblem.png",
    position: new Vector3(0,0,PLAYER_BASE_Z),
    allCards: [],
    cardsInPlay: [1, 3],
    owner: "player",
    boardSide: "N",
  },
  {
    id: 200,
    name: "Opponent",
    clan: "Lancastrians",
    textureUrl: "/textures/White_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: [],
    cardsInPlay: [2, 4],
    owner: "opponent",
    boardSide: "S",
  },
  {
    id: 300,
    name: "Opponent_2",
    clan: "Lancastrians",
    textureUrl: "/textures/White_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: [],
    cardsInPlay: [2, 4],
    owner: "opponent",
    boardSide: "E",
  },
  {
    id: 400,
    name: "Player_2",
    clan: "Yorkists",
    textureUrl: "/textures/Red_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: [],
    cardsInPlay: [1, 3],
    owner: "player",
    boardSide: "W",
  },
];
    