import { Vector3 } from "three";
import type { Card, Player } from "@/types";
import { PLAYER_BASE_Z, SPELLCASTER, DARK, LIGHT, DRAGON, EARTH, WARRIOR, SPELL, FIEND, NORMALMONSTER, EFFECTMONSTER, FUSIONMONSTER, RITUALMONSTER, NORMALSPELL } from "@/const";

export const cards: Card[] = [
  {
    id: 1,
    name: "Dark Magician",
    attack: 2500,
    defense: 2100,
    description: "The ultimate wizard in terms of attack and defense.",
    owner: "player",
    position: new Vector3(2, -5, 0.11),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 8,
    monster: SPELLCASTER,
    type: NORMALMONSTER,
    attribute: DARK,
    templateUrl: "/textures/normalTemplate.png",
    textureUrl: "/cards/Dark_Magician.png",
    maskUrl: "/cards/Dark_Magician_Mask.png",
  },
  {
    id: 2,
    name: "Blue-Eyes White Dragon",
    attack: 3000,
    defense: 2500,
    description: "This legendary dragon is a powerful engine of destruction.",
    owner: "opponent",
    position: new Vector3(0, 4, 0.12),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 8,
    monster: DRAGON,
    type: NORMALMONSTER,
    attribute: LIGHT,
    textureUrl: "/cards/Blue_Eyes_White_Dragon.png",
    templateUrl: "/textures/normalTemplate.png",
    maskUrl: "/cards/Blue_Eyes_White_Dragon_Mask.png",
  },
  {
    id: 3,
    name: "Dark Magician Girl",
    attack: 2000,
    defense: 1600,
    description: "The Dark Magician's younger sister. She wields the power of the Dark Magician.",
    owner: "player",
    position: new Vector3(-2, -5, 0.13),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 6,
    monster: SPELLCASTER,
    type: EFFECTMONSTER,
    attribute: DARK,
    templateUrl: "/textures/effectTemplate.png",
    textureUrl: "/cards/Dark_Magician_Girl.png",
    maskUrl: "/cards/Dark_Magician_Girl_Mask.png",
  },
  {
    id: 4,
    name: "Red-Eyes Black Dragon",
    attack: 2400,
    defense: 2000,
    description: "A ferocious dragon with a deadly attack.",
    owner: "opponent",
    position: new Vector3(2, 5, 0.14),
    isFaceDown: false,
    isDefenseMode: false,
    rarity: "common",
    level: 7,
    monster: DRAGON,
    type: NORMALMONSTER,
    attribute: DARK,
    templateUrl: "/textures/normalTemplate.png",
    textureUrl: "/cards/Red_Eyes_Black_Dragon.png",
  },
  {
    id: 5,
    name: "Blue-Eyes White Dragon",
    attack: 3000,
    defense: 2500,
    description: "This legendary dragon is a powerful engine of destruction.",
    owner: "player",
    position: new Vector3(0, -2, 0.12),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 8,
    monster: DRAGON,
    type: NORMALMONSTER,
    attribute: LIGHT,
    templateUrl: "/textures/normalTemplate.png",
    textureUrl: "/cards/Blue_Eyes_White_Dragon.png",
    maskUrl: "/cards/Blue_Eyes_White_Dragon_Mask.png",
  },
  {
    id: 6,
    name: "Blue-Eyes Ultimate Dragon",
    attack: 4500,
    defense: 3800,
    description: "This legendary dragon is a powerful engine of destruction.",
    owner: "player",
    position: new Vector3(1, -2, 0.12),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "ultra",
    level: 12,
    monster: DRAGON,
    type: FUSIONMONSTER,
    attribute: LIGHT,
    templateUrl: "/textures/fusionTemplate.png",
    textureUrl: "/cards/Blue_Eyes_Ultimate_Dragon.png",
    maskUrl: "/cards/Blue_Eyes_Ultimate_Dragon_Mask.png",
  },
  {
    id: 7,
    name: "Black Luster Soldier",
    attack: 3000,
    defense: 2500,
    description: "This monster can only be Ritual Summoned with the Ritual Spell Card, Black Luster Ritual.",
    owner: "player",
    position: new Vector3(-1, -5, 0.13),
    isFaceDown: false,
    isDefenseMode: false,
    rarity: "common",
    level: 8,
    monster: WARRIOR,
    type: RITUALMONSTER,
    attribute: EARTH,
    templateUrl: "/textures/ritualTemplate.png",
    textureUrl: "/cards/Black_Luster_Soldier.png",
    // maskUrl: "/cards/Black_Luster_Soldier_Mask.png",
  },
  {
    id: 8,
    name: "Change of Heart",
    attack: -1,
    defense: -1,
    description: "Target 1 monster your opponent controls; change its ATK and DEF to 0.",
    owner: "player",
    position: new Vector3(0, -3, 0.11),
    isFaceDown: true,
    isDefenseMode: false,
    rarity: "common",
    monster: null,
    type: NORMALSPELL,
    level: 0,
    attribute: SPELL,
    templateUrl: "/textures/spellTemplate.png",
    textureUrl: "/cards/Change_of_Heart.png",
    // maskUrl: "/cards/Change_of_Heart_Mask.png",
  },
  {
    id: 9,
    name: "Summoned Skull",
    attack: 2500,
    defense: 1200,
    description: "A fiend with dark powers for confusing the enemy. Among the Fiend-Type monsters, the monster boasts considerable force.",
    owner: "player",
    position: new Vector3(0, -4, 0.11),
    isFaceDown: false,
    isDefenseMode: false,
    rarity: "ultra",
    level: 6,
    monster: FIEND,
    type: NORMALMONSTER,
    attribute: DARK,
    templateUrl: "/textures/normalTemplate.png",
    textureUrl: "/cards/Summoned_Skull.png",
    maskUrl: "/cards/Summoned_Skull_Mask.png",
  }
];

// Helper to generate deck cards
function generateDeck(owner: 'player' | 'opponent', startId: number): Card[] {
  const deck: Card[] = [];
  let idCounter = startId;
  const templates = cards.filter(c => c.owner === 'player'); // Use player cards as templates

  // Create 40 cards
  for (let i = 0; i < 40; i++) {
    const template = templates[i % templates.length];
    deck.push({
      ...template,
      id: idCounter++,
      owner: owner,
      position: new Vector3(0, 0, -10), // Hidden initially
      isFaceDown: true,
      isDefenseMode: true,
    });
  }
  return deck;
}

const playerDeckCards = generateDeck('player', 1000);
const opponentDeckCards = generateDeck('opponent', 2000);

// Combine initial board cards with generated decks for "allCards"
// Actually, gameStore.cards tracks board cards.
// Player.allCards should probably track ALL cards owned by player (deck + hand + graveyard + field)
// For now, let's just make sure we populate the deck IDs.

export const players: Player[] = [
  {
    id: 100,
    name: "Player_1",
    clan: "Yorkists",
    textureUrl: "/textures/Red_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: playerDeckCards, // Only deck cards for now? Or include the initial ones? 
    // Initial cards 1,3 are hardcoded on board. Let's add them to deck tracking or separate?
    // Plan says: "Initialize player's deck with these IDs".
    // Let's assume the cards array exported above IS the board state.
    // And playerDeckCards are the OFF-BOARD deck.
    deck: playerDeckCards.map(c => c.id),
    hand: [],
    graveyard: [],
    cardsInPlay: [1, 3], // These are the hardcoded ones in 'cards' array
    owner: "player",
    boardSide: "S",
    firstMove: true,
  },
  {
    id: 200,
    name: "Opponent",
    clan: "Lancastrians",
    textureUrl: "/textures/White_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: opponentDeckCards,
    deck: opponentDeckCards.map(c => c.id),
    hand: [],
    graveyard: [],
    cardsInPlay: [2, 4],
    owner: "opponent",
    boardSide: "N",
    firstMove: false,
  },
  {
    id: 300,
    name: "Opponent_2",
    clan: "Lancastrians",
    textureUrl: "/textures/White_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: [],
    deck: [],
    hand: [],
    graveyard: [],
    cardsInPlay: [2, 4],
    owner: "opponent",
    boardSide: "E",
    firstMove: false,
  },
  {
    id: 400,
    name: "Player_2",
    clan: "Yorkists",
    textureUrl: "/textures/Red_rose_emblem.png",
    position: new Vector3(0, 0, PLAYER_BASE_Z),
    allCards: [],
    deck: [],
    hand: [],
    graveyard: [],
    cardsInPlay: [1, 3],
    owner: "player",
    boardSide: "W",
    firstMove: false,
  },
];
